del debug\*.obj
del debug\*.sbr
del debug\*.enc
del debug\*.tli
del debug\*.tlh
del debug\*.pcb
del debug\*.pch
del debug\*.res
del debug\*.ilk
del debug\*.bsc
del debug\*.exp
del debug\*.lib
del debug\*.pdb
del debug\*.idb
del debug\*.dep
del debug\BuildLog.htm
del debug\*.embed.manifest
del debug\*.embed.manifest.res
del debug\*.intermediate.manifest
del release\*.obj
del release\*.sbr
del release\*.enc
del release\*.tli
del release\*.tlh
del release\*.pcb
del release\*.pch
del release\*.res
del release\*.exp
del release\*.lib
del release\*.ilk
del release\*.bsc
del release\*.pdb
del release\*.idb
del release\*.dep
del release\BuildLog.htm
del release\*.embed.manifest
del release\*.embed.manifest.res
del release\*.intermediate.manifest

del *.tmp
del *.ncb
attrib -h -r -s *.suo
del *.suo
del *.opt
del *.plg
del *.vcproj.*.user