rmdir /q/s ipch

del debug\*.obj
del debug\*.sbr
del debug\*.enc
del debug\*.tli
del debug\*.tlh
del debug\*.pcb
del debug\*.pch
del debug\*.res
del debug\*.ilk
del debug\*.bsc
del debug\*.exp
del debug\*.pdb
del debug\*.idb
del debug\*.dep
del debug\BuildLog.htm
del debug\*.embed.manifest
del debug\*.embed.manifest.res
del debug\*.intermediate.manifest
del debug\*.tlog
del debug\*.lastbuildstate
del debug\*.log
del debug\*.cache
del debug\*.unsuccessfulbuild

del x64\debug\*.obj
del x64\debug\*.sbr
del x64\debug\*.enc
del x64\debug\*.tli
del x64\debug\*.tlh
del x64\debug\*.pcb
del x64\debug\*.pch
del x64\debug\*.res
del x64\debug\*.ilk
del x64\debug\*.bsc
del x64\debug\*.exp
del x64\debug\*.pdb
del x64\debug\*.idb
del x64\debug\*.dep
del x64\debug\BuildLog.htm
del x64\debug\*.embed.manifest
del x64\debug\*.embed.manifest.res
del x64\debug\*.intermediate.manifest
del x64\debug\*.tlog
del x64\debug\*.lastbuildstate
del x64\debug\*.log
del x64\debug\*.cache

del release\*.res
del release\*.ilk
del release\*.bsc
del release\*.exp
del release\*.pdb
del release\*.idb
del release\*.dep
del release\BuildLog.htm
del release\*.embed.manifest
del release\*.embed.manifest.res
del release\*.intermediate.manifest
del release\*.tlog
del release\*.lastbuildstate
del release\*.log
del release\*.cache
del release\*.unsuccessfulbuild

del x64\release\*.obj
del x64\release\*.sbr
del x64\release\*.enc
del x64\release\*.tli
del x64\release\*.tlh
del x64\release\*.pcb
del x64\release\*.pch
del x64\release\*.res
del x64\release\*.ilk
del x64\release\*.bsc
del x64\release\*.exp
del x64\release\*.pdb
del x64\release\*.idb
del x64\release\*.dep
del x64\release\BuildLog.htm
del x64\release\*.embed.manifest
del x64\release\*.embed.manifest.res
del x64\release\*.intermediate.manifest
del x64\release\*.tlog
del x64\release\*.lastbuildstate
del x64\release\*.log
del x64\release\*.cache

del *.sdf
del *.tmp
del *.ncb
attrib -h -r -s *.suo
del *.suo
del *.vcproj.*.user