all:
	g++ -oconvert --std=c++17 convert_image.cpp png.cpp -lpng fs_tools.cpp megalz/mhmt-emit.c megalz/mhmt-globals.c megalz/mhmt-hash.c megalz/mhmt-lz.c megalz/mhmt-optimal.c megalz/mhmt-pack.c megalz/mhmt-tb.c

clear:
	rm -r -f convert