// autogenerated
const fileList = [
    'files/2048.rk',
    'files/basic80.rk',
    'files/circus.rk',
    'files/klad.rk',
    'files/kosoban.rk',
    'files/lines.rk',
    'files/reversi.rk',
    'files/tetris.rk',
];
